Repository nextcloud/integration_openproject, pull requests merged in 2025-02, with the labels that each got.

#762 docs: update release docs
  docs/release.md
Labels: feedback-requested

#753 feat: show errors when user_oidc app is not available
  CHANGELOG.md
  src/components/AdminSettings.vue
  src/components/PersonalSettings.vue
  src/components/admin/FormHeading.vue
  src/components/admin/TextInput.vue
  src/components/settings/ErrorNote.vue
  src/constants/links.js
  src/constants/messages.js
  src/views/Dashboard.vue
  tests/jest/components/AdminSettings.spec.js
  tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
  tests/jest/components/admin/TextInput.spec.js
  tests/jest/components/settings/ErrorNote.spec.js
  tests/jest/components/settings/__snapshots__/ErrorNote.spec.js.snap
  tests/jest/views/Dashboard.spec.js
Labels: enhancement, feedback-requested

#769 Group the API endpoints that contact OP in an OCS controller
  CHANGELOG.md
  appinfo/routes.php
  lib/Controller/OpenProjectAPIController.php
  lib/Controller/OpenProjectController.php
  lib/Service/OpenProjectAPIService.php
  lib/Settings/Admin.php
  src/components/AdminSettings.vue
  src/components/tab/SearchInput.vue
  src/utils/workpackageHelper.js
  src/views/CreateWorkPackageModal.vue
  src/views/Dashboard.vue
  src/views/LinkMultipleFilesModal.vue
  src/views/ProjectsTab.vue
  src/views/WorkPackagePickerElement.vue
  tests/jest/components/tab/SearchInput.spec.js
  tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
  tests/jest/views/CreateWorkpackageModal.spec.js
  tests/jest/views/Dashboard.spec.js
  tests/jest/views/LinkMultipleFilesModal.spec.js
  tests/jest/views/ProjectsTab.spec.js
  tests/jest/views/__snapshots__/Dashboard.spec.js.snap
  tests/lib/Controller/OpenProjectAPIControllerTest.php
  tests/lib/Controller/OpenProjectControllerTest.php
  tests/lib/Service/OpenProjectAPIServiceTest.php
Labels: enhancement, 3. to review
