Repository nextcloud/integration_openproject, pull requests merged in 2025-03, with the labels that each got.

#781 ci: dynamic job matrix creation
  .github/scripts/generate-matrix.sh
  .github/workflows/nighlty-ci-release-branch.yml
  .github/workflows/shared_workflow.yml
Labels: backport

#776 build: add NC compose setup to use specific server branch
  dev/.env
  dev/compose.yaml
  dev/nextcloud.sh
  dev/nextcloud/config.php
  dev/nextcloud/hooks/after-install.sh
  dev/nextcloud/hooks/before-install.sh
Labels: backport

#768 [WP #60683]display error if oidc apps not supported
  CHANGELOG.md
  lib/Service/OpenProjectAPIService.php
  lib/Settings/Admin.php
  src/components/AdminSettings.vue
  src/constants/messages.js
  tests/jest/components/AdminSettings.spec.js
  tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
  tests/lib/Service/OpenProjectAPIServiceTest.php
Labels: feedback-requested

#797 feat: add option to enable token exchange
  CHANGELOG.md
  bootstrap.php
  lib/Controller/ConfigController.php
  lib/ExchangedTokenRequestedEventHelper.php
  lib/Service/OpenProjectAPIService.php
  lib/Settings/Admin.php
  lib/TokenEventFactory.php
  psalm.xml
  src/components/AdminSettings.vue
  src/constants/messages.js
  tests/jest/components/AdminSettings.spec.js
  tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
  tests/lib/Service/OpenProjectAPIServiceTest.php
  tests/lib/TokenEventFactoryTest.php
Labels: enhancement
