Repository nextcloud/integration_openproject, pull requests merged in 2025-01, with the labels that each got.

#737 Added authentication method selection in integration setup
  .github/workflows/shared_workflow.yml
  CHANGELOG.md
  lib/Controller/ConfigController.php
  lib/Controller/OpenProjectAPIController.php
  lib/Dashboard/OpenProjectWidget.php
  lib/ExchangedTokenRequestedEventHelper.php
  lib/Listener/LoadAdditionalScriptsListener.php
  lib/Listener/LoadSidebarScript.php
  lib/Listener/OpenProjectReferenceListener.php
  lib/Search/OpenProjectSearchProvider.php
  lib/Service/OpenProjectAPIService.php
  lib/Settings/Admin.php
  lib/Settings/Personal.php
  psalm.xml
  src/components/AdminSettings.vue
  src/components/PersonalSettings.vue
  src/components/tab/EmptyContent.vue
  src/utils.js
  src/views/Dashboard.vue
  src/views/LinkMultipleFilesModal.vue
  src/views/ProjectsTab.vue
  src/views/WorkPackagePickerElement.vue
  tests/jest/components/AdminSettings.spec.js
  tests/jest/components/PersonalSettings.spec.js
  tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
  tests/jest/components/tab/EmptyContent.spec.js
  tests/lib/Controller/ConfigControllerTest.php
  tests/lib/Controller/OpenProjectAPIControllerTest.php
  tests/lib/Service/OpenProjectAPIServiceTest.php
  tests/lib/Settings/PersonalTest.php
Labels: feedback-requested

#755 chore: setup new keycloak realm on startup
  dev/keycloak.yaml
  dev/opnc-realm.json
  docs/setup_nc_op__full.md
Labels: documentation, backport

#757 chore: add linting make targets
  .github/workflows/shared_workflow.yml
  bootstrap.php
  composer.json
  makefile
Labels: backport
